inherit_from:
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Next:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Proc:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/WordArray:
  Enabled: false

Rails/Output:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# needs major refactorings before we can improve
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 72
Metrics/CyclomaticComplexity:
  Max: 36
Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 6

Lint/UnusedMethodArgument:
  Enabled: false

# JobTemplates use this for inputs, we should probably whitelist classes
Security/YAMLLoad:
  Enabled: false

# rake task over 50 LOCs
Metrics/BlockLength:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false
