export const SYNC_SETTINGS_REQUEST = 'SYNC_SETTINGS_REQUEST';
export const SYNC_SETTINGS_SUCCESS = 'SYNC_SETTINGS_SUCCESS';
export const SYNC_SETTINGS_FAILURE = 'SYNC_SETTINGS_FAILURE';

export const TEMPLATESYNC_FORM_SUBMITTED = 'TEMPLATESYNC_FORM_SUBMITTED';
export const SYNC_RESULT_PAGINATION_CHANGE = 'SYNC_RESULT_PAGINATION_CHANGE';
